/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package srishti;
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JTable;
import java.util.Calendar;
/**
 *
 * @author srishtiparulekar
 */
public class adminDash extends javax.swing.JFrame {
   
    /**
     * Creates new form adminDash
     */
    DefaultTableModel dt;
    public adminDash() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void setDefaultValues() {
    EmpName2.setText("User Not Found");
    EmpDesignation2.setText("Unknown");
    
    }
    public adminDash(String username, String fname, String lname, String userrole,String email, String address, String phone,String dob) {
    initComponents();
    this.username = username;
    this.fname = fname;
    this.lname = lname;
    this.userrole = userrole;
    this.email = email;
    this.address = address;
    this.phone = phone;
    this.dob = dob;
    try{
    Connection con = ConnectionProvider.getCon();
    Statement stmt = null;
    stmt = con.createStatement();
    String sql = "SELECT userID WHERE username ='" + username + "';";
    ResultSet rs = stmt.executeQuery(sql);
    myuserID = rs.getInt("userID");
    String sql2 = "SELECT password WHERE username = '" + username + "';";
    
    rs = stmt.executeQuery(sql2);
    password = rs.getString("userpassword");
    } 
    catch (SQLException e){
        e.printStackTrace();
    }
    
    
    setLocationRelativeTo(null);
    EmpName2.setText(this.fname + " " + this.lname);
    jLabel31.setText(this.fname + " " + this.lname);
//    EmpName.setText(EmpName2.getText());
    EmpDesignation2.setText(this.userrole);
    //EPUDA
    jLabel32.setText(email);
    jLabel33.setText(phone);
    jLabel34.setText(username);
    jLabel35.setText(dob);
    jLabel36.setText(address);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel2 = new javax.swing.JPanel();
        sidePanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        EmpName2 = new javax.swing.JLabel();
        EmpDesignation2 = new javax.swing.JLabel();
        btn8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        centrePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        searchUserDetails = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        EnterValue = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchUserID = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(153, 153, 153)));

        sidePanel2.setBackground(new java.awt.Color(0, 102, 102));
        sidePanel2.setPreferredSize(new java.awt.Dimension(200, 700));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-teenager-female-50.png"))); // NOI18N

        EmpName2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EmpName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpName2.setText("EmployeeName");
        EmpName2.setPreferredSize(new java.awt.Dimension(200, 17));

        EmpDesignation2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EmpDesignation2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpDesignation2.setText("EmployeeDesignation");

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("View Profile");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout btn8Layout = new javax.swing.GroupLayout(btn8);
        btn8.setLayout(btn8Layout);
        btn8Layout.setHorizontalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btn8Layout.setVerticalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-database-50 (1).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search Database");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-database-administrator-50 (1).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Update Database");

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-get-revenue-50.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Revenue Generated");

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Log Out");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout btn6Layout = new javax.swing.GroupLayout(btn6);
        btn6.setLayout(btn6Layout);
        btn6Layout.setHorizontalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn6Layout.setVerticalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanel2Layout = new javax.swing.GroupLayout(sidePanel2);
        sidePanel2.setLayout(sidePanel2Layout);
        sidePanel2Layout.setHorizontalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel2Layout.createSequentialGroup()
                .addGroup(sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpDesignation2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        sidePanel2Layout.setVerticalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel2Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(EmpDesignation2)
                .addGap(9, 9, 9)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        centrePanel.setBackground(new java.awt.Color(153, 153, 153));
        centrePanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setText("Personal details");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Name: ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Registered Email:");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Registered Mobile Number:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("Username:");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("Date of Birth:");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("Address:");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("EmpName");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setText("EmpEmail");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setText("EmpPhono");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel34.setText("EmpUserName");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel35.setText("EmpDOB");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel36.setText("EmpAddress");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Contact Other Admins");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33))))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel32))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel33))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel34))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel35))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel36))
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        centrePanel.add(jPanel1, "card2");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel14.setText("User Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "First Name", "Last Name", "Email", "Phone Number", "Date of Birth", "Address", "Username"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Admin", "User", "NGO", "Volunteer", "Donor", " " }));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Filter your search: ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Search by userID or Username:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Choose any of the given filters to search for the required user's details:");

        searchUserDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchUserDetails.setText("Search");
        searchUserDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchUserDetailsMouseClicked(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Admin", "User", "NGO", "Donor", "Volunteer", " " }));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Search Count:");

        EnterValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterValueActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "donorID", "ngoID", "userID", "Amount Contributed", "Time of Donation"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "volunteerID", "userID", "ngoID", "skills", "interests", "availability"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ngoID", "catID", "ngoName", "city", "email", "about"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(180, 180, 180)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(EnterValue, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(searchUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)))
                                .addGap(190, 190, 190)
                                .addComponent(jLabel20))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(211, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jLabel14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2)
                            .addComponent(jComboBox1))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(EnterValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(searchUserDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        centrePanel.add(jPanel3, "card4");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("Update Database");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Search by UserID: ");

        searchUserID.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        txtFName.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtFName.setForeground(new java.awt.Color(153, 153, 153));
        txtFName.setText("First Name");
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtLName.setForeground(new java.awt.Color(153, 153, 153));
        txtLName.setText("Last Name");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("Email");

        txtPhone.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(153, 153, 153));
        txtPhone.setText("Phone Number");

        txtAddress.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setText("Address");

        txtUsername.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setText("username");

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddress)
                            .addComponent(txtFName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(searchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLName)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(txtUsername)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(jButton3)))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        centrePanel.add(jPanel4, "card5");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel16.setText("Revenue");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Month", "Revenue"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NGOID", "NGOName", "Total Revenue"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel16)
                .addGap(116, 116, 116)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        centrePanel.add(jPanel5, "card6");

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(centrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_btn3MouseClicked
//     
//    private void displayMonthWiseDonations() {                                          
//    try {
//        Connection con = ConnectionProvider.getCon();
//        Statement stmt = con.createStatement();
//        // Get the current month and year
//        Calendar cal = Calendar.getInstance();
//        int currentMonth = cal.get(Calendar.MONTH) + 1; // Calendar.MONTH is zero-based
//        int currentYear = cal.get(Calendar.YEAR);
//        
//        // Construct the SQL query to select donations for the current month and year
//        String query = "SELECT DATE_FORMAT(timeOfDonation, '%Y-%m') AS donationMonth, SUM(amountContributed) AS totalDonation " +
//                       "FROM donor " +
//                       "WHERE YEAR(timeOfDonation) = " + currentYear + " AND MONTH(timeOfDonation) = " + currentMonth +
//                       " GROUP BY DATE_FORMAT(timeOfDonation, '%Y-%m')";
//        
//        ResultSet rs = stmt.executeQuery(query);
//        
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Month");
//        model.addColumn("Total Donation");
//        
//        while (rs.next()) {
//            String donationMonth = rs.getString("donationMonth");
//            int totalDonation = rs.getInt("totalDonation");
//            model.addRow(new Object[]{donationMonth, totalDonation});
//        }
//        
//        JTable table = new JTable(model);
//        JOptionPane.showMessageDialog(null, table);
//        
//        rs.close();
//        stmt.close();
//        con.close();
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
//        e.printStackTrace();
//    }
//}
    private void displayMonthWiseDonations() {                                          
    try {
        Connection con = ConnectionProvider.getCon();
        Statement stmt = con.createStatement();
        String query = "SELECT MONTH(timeOfDonation) AS donationMonth, SUM(amountContributed) AS totalDonation " +
                       "FROM donor WHERE YEAR(timeOfDonation) = 2024 GROUP BY MONTH(timeOfDonation)";
        ResultSet rs = stmt.executeQuery(query);
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Month");
        model.addColumn("Total Donation");
        
        while (rs.next()) {
            int donationMonth = rs.getInt("donationMonth");
            String monthName = getMonthName(donationMonth);
            int totalDonation = rs.getInt("totalDonation");
            model.addRow(new Object[]{monthName, totalDonation});
        }
        
        jTable2.setModel(model); // Set the model to jTable2
        
        rs.close();
        stmt.close();
        con.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        displayRevenueInfo();
        displayMonthWiseDonations();
        jPanel1.setVisible(false);
        
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        
        jPanel5.setVisible(true);
        
    }//GEN-LAST:event_btn4MouseClicked
//private void displayRevenueInfo() {
//        try {
//            Connection con = ConnectionProvider.getCon();
//
//            // Display revenue month-wise
//            String sql = "SELECT MONTH(timeOfDonation) AS month, SUM(amountContributed) AS revenue FROM donor WHERE YEAR(timeOfDonation) = 2023 GROUP BY MONTH(timeOfDonation)";
//            PreparedStatement stmt = con.prepareStatement(sql);
//            ResultSet rs = stmt.executeQuery();
//
//            DefaultTableModel monthModel = new DefaultTableModel();
//            monthModel.addColumn("Month");
//            monthModel.addColumn("Revenue");
//
//            while (rs.next()) {
//                String month = getMonthName(rs.getInt("month"));
//                int revenue = rs.getInt("revenue");
//                monthModel.addRow(new Object[]{month, revenue});
//            }
//
//            jTable2.setModel(monthModel);
//
//            // Display total revenue, NGO ID, and NGO name
//            String sql2 = "SELECT n.ngoID, n.ngoName, SUM(d.amountContributed) AS totalRevenue FROM ngo n JOIN donor d ON n.ngoID = d.ngo_id GROUP BY n.ngoID";
//            PreparedStatement stmt2 = con.prepareStatement(sql2);
//            ResultSet totalrs = stmt2.executeQuery();
//
//            DefaultTableModel totalRevenueModel = new DefaultTableModel();
//            totalRevenueModel.addColumn("NGO ID");
//            totalRevenueModel.addColumn("NGO Name");
//            totalRevenueModel.addColumn("Total Revenue");
//
//            while (totalrs.next()) {
//                int ngoID = totalrs.getInt("ngoID");
//                String ngoName = totalrs.getString("ngoName");
//                int totalRevenue = totalrs.getInt("totalRevenue");
//                totalRevenueModel.addRow(new Object[]{ngoID, ngoName, totalRevenue});
//            }
//
//            jTable3.setModel(totalRevenueModel);
//
//            // Close resources
//            rs.close();
//            stmt.close();
//            totalrs.close();
//            stmt2.close();
//            con.close();
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
//            e.printStackTrace();
//        }
//    }
    private void displayRevenueInfo() {
    try {
        Connection con = ConnectionProvider.getCon();

//        // Display revenue month-wise
//        String sql = "SELECT MONTH(timeOfDonation) AS month, SUM(amountContributed) AS revenue FROM donor WHERE YEAR(timeOfDonation) = 2023 GROUP BY MONTH(timeOfDonation)";
//        PreparedStatement stmt = con.prepareStatement(sql);
//        ResultSet rs = stmt.executeQuery();
//


          DefaultTableModel monthModel = new DefaultTableModel();
//        monthModel.addColumn("Month");
//        monthModel.addColumn("Revenue");
//
//        while (rs.next()) {
//            String month = getMonthName(rs.getInt("month"));
//            int revenue = rs.getInt("revenue");
//            monthModel.addRow(new Object[]{month, revenue});
//        }

        jTable2.setModel(monthModel);

        // Display total revenue, NGO ID, and NGO name
        String sql2 = "SELECT n.ngoID, n.ngoName, SUM(d.amountContributed) AS totalRevenue FROM ngo n JOIN donor d ON n.ngoID = d.ngo_id GROUP BY n.ngoID";
        PreparedStatement stmt2 = con.prepareStatement(sql2);
        ResultSet totalrs = stmt2.executeQuery();

        DefaultTableModel totalRevenueModel = new DefaultTableModel();
        totalRevenueModel.addColumn("NGO ID");
        totalRevenueModel.addColumn("NGO Name");
        totalRevenueModel.addColumn("Total Revenue");

        while (totalrs.next()) {
            int ngoID = totalrs.getInt("ngoID");
            String ngoName = totalrs.getString("ngoName");
            int totalRevenue = totalrs.getInt("totalRevenue");
            totalRevenueModel.addRow(new Object[]{ngoID, ngoName, totalRevenue});
        }

        jTable3.setModel(totalRevenueModel);

        // Display month-wise donations
        displayMonthWiseDonations();

        // Close resources
//        rs.close();
//        stmt.close();
        totalrs.close();
        stmt2.close();
        con.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}


    // Function to get month name from month number
    private String getMonthName(int month) {
        String[] monthNames = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
        return monthNames[month - 1];
    }

     
    
    // Other code...
    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // Logout button
        int a = JOptionPane.showConfirmDialog(null,"Do you want to log out?", "Log out",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn6MouseClicked

/**/

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        Connection con = ConnectionProvider.getCon();
        String sql = "SELECT fname, lname, email, phone FROM person WHERE userrole = 'Admin' AND username != ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, username); 
        ResultSet rs = stmt.executeQuery();

        StringBuilder message = new StringBuilder();
        while (rs.next()) {
            String name = rs.getString("fname") + " " + rs.getString("lname");
            String email = rs.getString("email");
            String phone = rs.getString("phone");
            message.append("Name: ").append(name).append("\n")
                   .append("Email: ").append(email).append("\n")
                   .append("Phone: ").append(phone).append("\n\n");
        }
        con.close();

        if (message.length() > 0) {
            JOptionPane.showMessageDialog(this, message.toString(), "Contact Other Admins", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No other admins found.", "Contact Other Admins", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Authenticate(username).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
/**/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        // Get the search keyword from jTextField2
    //String searchKeyword = searchUserID.getText().trim();
    
    
    
    
    String searchKeyword = searchUserID.getText().trim();
    updationUserID = Integer.parseInt(searchKeyword);
//    this.updationUserID = updationUserID;
    
    
    
    // Check if the search keyword is not empty
    if (!searchKeyword.isEmpty()) {
        try {
            Connection con = ConnectionProvider.getCon();
            String sql = "SELECT * FROM person WHERE userID = " + updationUserID + ";";
//            PreparedStatement stmt = con.prepareStatement(sql);
//            
//            // Set the search keyword as parameter values
//            stmt.setString(1, searchKeyword);
//            
            Statement stmt = null;
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Check if any record is found
            if (rs.next()) {
                // Retrieve values from ResultSet and set them to text fields
                txtFName.setText(rs.getString("fname"));
                txtLName.setText(rs.getString("lname"));
                txtAddress.setText(rs.getString("address"));
                
                
                txtPhone.setText(rs.getString("phone"));
                txtEmail.setText(rs.getString("email"));
                txtUsername.setText(rs.getString("username"));
                
            } else {
                JOptionPane.showMessageDialog(null, "No record found.");
                // Clear text fields if no record is found
                txtFName.setText("");
                txtLName.setText("");
                txtAddress.setText("");
                
                txtPhone.setText("");
                txtEmail.setText("");
                txtUsername.setText("");
                
                
            }

            // Close resources
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please enter a search keyword.");
    }

    }//GEN-LAST:event_jButton5MouseClicked


    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    String newfname = txtFName.getText();
    String newlname = txtLName.getText();
    String newaddress = txtAddress.getText();
    String newphone = txtPhone.getText();
    String newemail = txtEmail.getText();

    // Check if any field is empty
    if (newfname.isEmpty() || newlname.isEmpty() || newaddress.isEmpty() || newphone.isEmpty() || newemail.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields");
        return;
    }

    try {
        Connection con = ConnectionProvider.getCon();
        String sql = "UPDATE person SET fname=?, lname=?, address=?,  phone=?, email=? WHERE userID=?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, newfname);
        stmt.setString(2, newlname);
        stmt.setString(3, newaddress);
//       
        stmt.setString(4, newphone);
        stmt.setString(5, newemail);
        
    
        stmt.setInt(6, updationUserID); 
        

        int rowsAffected = stmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Person information updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update person information");
        }

        
        stmt.close();
        con.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton3MouseClicked
    private int executeCountQuery(String sql) throws SQLException {
    Connection con = ConnectionProvider.getCon();
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
    rs.next();
    int count = rs.getInt(1);
    
    rs.close();
    stmt.close();
    con.close();
    return count;
}
/*
    private void searchUserDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserDetailsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel donorTableModel = (DefaultTableModel) jTable4.getModel();
        DefaultTableModel volunteerTableModel = (DefaultTableModel) jTable5.getModel();
        DefaultTableModel ngoTableModel = (DefaultTableModel) jTable6.getModel();
    try {
        Connection con = ConnectionProvider.getCon();
        String searchText = EnterValue.getText().trim();
        String selectedValue1 = (String) jComboBox1.getSelectedItem();
        String selectedValue2 = (String) jComboBox2.getSelectedItem();
        
        if (!searchText.isEmpty()) {
            // Search by userID or username
            String sql = "SELECT * FROM person WHERE userID = ? OR username = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, searchText); // Set userID parameter
            stmt.setString(2, searchText); // Set username parameter
            executeQuery(stmt, model, con);
            
        } 
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Admins")) {
            // Count of Admins
              Statement stmt = con.createStatement();
              String sql = "SELECT COUNT(*) FROM person WHERE userrole = 'Admin'";
              ResultSet rs = stmt.executeQuery(sql);
              rs.next();
              int count = rs.getInt(1);
              JOptionPane.showMessageDialog(null, "Total number of Admins: " + count);
        }
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Users")) {
            // Count of Users
              Statement stmt = con.createStatement();
              String sql = "SELECT COUNT(*) FROM person WHERE userrole = 'User'";
              ResultSet rs = stmt.executeQuery(sql);
              rs.next();
              int count = rs.getInt(1);
              JOptionPane.showMessageDialog(null, "Total number of Users: " + count);
        }
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("NGOs")) {
            // Count of NGOs
              String sql = "SELECT COUNT(*) FROM ngo";
              JOptionPane.showMessageDialog(null, "Total number of NGOs: " + executeCountQuery(sql));
        }
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Volunteers")) {
            // Count of Volunteers
              String sql = "SELECT COUNT(*) FROM volunteer";
              JOptionPane.showMessageDialog(null, "Total number of Volunteers: " + executeCountQuery(sql));
        }
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Donors")) {
            // Count of Donors
              String sql = "SELECT COUNT(*) FROM donor";
              JOptionPane.showMessageDialog(null, "Total number of Donors: " + executeCountQuery(sql));
        }
        
        else if (selectedValue1 != null && !selectedValue1.equalsIgnoreCase("None")) {
            // Search by User Role
            if(selectedValue1.equals("Admin") || selectedValue1.equals("NGO") || selectedValue1.equals("User") ){
            String sql = "SELECT * FROM person WHERE userrole = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, selectedValue1);
            executeQuery(stmt, model, con);
            }
            
            else {
                
                if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("NGOs")) {
            // Count of NGOs
            String sql = "SELECT * FROM ngo";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            ngoTableModel.setRowCount(0); // Clear previous data
            while (rs.next()) {
                // Add row to the ngo table model
                ngoTableModel.addRow(new Object[]{
                    rs.getInt("ngoId"),
                    rs.getInt("catID"),
                    rs.getString("ngoName"),
                    rs.getString("city"),
                    rs.getString("email"),
                    rs.getString("about"),
                    
                });
            }
            rs.close();
            stmt.close();
        }
                else if(selectedValue1.equals("Donor")){
            String sql2 = "SELECT * FROM donor";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            donorTableModel.setRowCount(0); // Clear previous data
            while (rs.next()) {
                // Add row to the donor table model
                donorTableModel.addRow(new Object[]{
                    rs.getInt("donorID"),
                    rs.getInt("ngo_id"),
                    rs.getInt("user_ID"),
                    rs.getInt("amountContributed"),
                    rs.getTimestamp("timeOfDonation")
                });
                        } }
            else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Volunteers")) {
            // Count of Volunteers
            String sql = "SELECT * FROM Volunteer";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            volunteerTableModel.setRowCount(0); // Clear previous data
            while (rs.next()) {
                // Add row to the volunteer table model
                volunteerTableModel.addRow(new Object[]{
                    rs.getInt("volunteerId"),
                    rs.getInt("user_id"),
                    rs.getInt("ngoID"),
                    rs.getString("skills"),
                    rs.getString("interests"),
                    rs.getString("availability")
                });
            }
            rs.close();
            stmt.close();
        }
        else if (selectedValue2 != null && selectedValue2.equalsIgnoreCase("Donors")) {
            // Count of Donors
            String sql = "SELECT * FROM donor";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            donorTableModel.setRowCount(0); // Clear previous data
            while (rs.next()) {
                // Add row to the donor table model
                donorTableModel.addRow(new Object[]{
                    rs.getInt("donorID"),
                    rs.getInt("ngo_id"),
                    rs.getInt("user_ID"),
                    rs.getInt("amountContributed"),
                    rs.getTimestamp("timeOfDonation")
                });
            }
        }   
        } else {
            // Print entire table
            String sql = "SELECT * FROM person";
            PreparedStatement stmt = con.prepareStatement(sql);
            executeQuery(stmt, model, con);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_searchUserDetailsMouseClicked
*/
    private void searchUserDetailsMouseClicked(java.awt.event.MouseEvent evt) {                                               
    DefaultTableModel userModel = (DefaultTableModel) jTable1.getModel();
    DefaultTableModel donorModel = (DefaultTableModel) jTable4.getModel();
    DefaultTableModel volunteerModel = (DefaultTableModel) jTable5.getModel();
    DefaultTableModel ngoModel = (DefaultTableModel) jTable6.getModel();

    try {
        Connection con = ConnectionProvider.getCon();
        String searchText = EnterValue.getText().trim();
        String selectedFilter = (String) jComboBox1.getSelectedItem();
        String selectedCount = (String) jComboBox2.getSelectedItem();

        if (!searchText.isEmpty()) {
            // Search by userID or username in all tables
            String userSql = "SELECT * FROM person WHERE userID = ? OR username = ?";
            PreparedStatement userStmt = con.prepareStatement(userSql);
            userStmt.setString(1, searchText); // Set userID parameter
            userStmt.setString(2, searchText); // Set username parameter
            executeQuery(userStmt, userModel, con);

            String donorSql = "SELECT * FROM donor WHERE user_ID = ?";
            PreparedStatement donorStmt = con.prepareStatement(donorSql);
            donorStmt.setString(1, searchText); // Set user_ID parameter
            executeQuery(donorStmt, donorModel, con);

            String volunteerSql = "SELECT * FROM Volunteer WHERE user_id = ?";
            PreparedStatement volunteerStmt = con.prepareStatement(volunteerSql);
            volunteerStmt.setString(1, searchText); // Set user_id parameter
            executeQuery(volunteerStmt, volunteerModel, con);

            String ngoSql = "SELECT * FROM ngo WHERE userid = ?";
            PreparedStatement ngoStmt = con.prepareStatement(ngoSql);
            ngoStmt.setString(1, searchText); // Set user_id parameter
            executeQuery(ngoStmt, ngoModel, con);

        } else if (selectedCount != null && !selectedCount.equalsIgnoreCase("None")) {
            // Count users based on selected role
            if(selectedCount.equals("Admin") || selectedCount.equals("User")){
            
            String countSql = "SELECT COUNT(*) FROM person WHERE userrole = ?";
            PreparedStatement countStmt = con.prepareStatement(countSql);
            countStmt.setString(1, selectedCount);
            ResultSet rs = countStmt.executeQuery();
            rs.next();
            
            
            
            int count = rs.getInt(1);
            JOptionPane.showMessageDialog(null, "Total number of " + selectedCount + ": " + count);}
            else if (selectedCount.equals("Volunteer") || selectedCount.equals("Donor") || selectedCount.equals("NGO")){
            //String countSql2 = "SELECT COUNT(*) FROM ?; ";
//            String countSql2 = "SELECT COUNT(*) FROM ?; ";
//
//            PreparedStatement countStmt2 = con.prepareStatement(countSql2);
//            countStmt2.setString(1, selectedCount);
//            ResultSet rs = countStmt2.executeQuery();
//            rs.next();
//            int count = rs.getInt(1);
//            JOptionPane.showMessageDialog(null, "Total number of " + selectedCount + ": " + count);
            
            String countSql2 = "SELECT COUNT(*) FROM " + selectedCount;
            PreparedStatement countStmt2 = con.prepareStatement(countSql2);
            ResultSet rs = countStmt2.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            JOptionPane.showMessageDialog(null, "Total number of " + selectedCount + ": " + count);

            
            
            }
            
        } else if (selectedFilter != null && !selectedFilter.equalsIgnoreCase("None")) {
            // Filter based on selected role
            String sql;
            if (selectedFilter.equalsIgnoreCase("Admin")) {
                sql = "SELECT * FROM person WHERE userrole = 'Admin'";
            } else if (selectedFilter.equalsIgnoreCase("Donor")) {
                sql = "SELECT * FROM donor";
            } else if (selectedFilter.equalsIgnoreCase("Volunteer")) {
                sql = "SELECT * FROM Volunteer";
            } else if (selectedFilter.equalsIgnoreCase("NGO")) {
                sql = "SELECT * FROM ngo";
            } else {
                // Invalid filter selected
                return;
            }
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            switch (selectedFilter) {
                case "Admin":
                    fillTable(rs, userModel);
                    break;
                case "Donor":
                    fillTable(rs, donorModel);
                    break;
                case "Volunteer":
                    fillTable(rs, volunteerModel);
                    break;
                case "NGO":
                    fillTable(rs, ngoModel);
                    break;
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
} 

private void executeQuery(PreparedStatement stmt, DefaultTableModel model, Connection con) throws SQLException {
    ResultSet rs = stmt.executeQuery();
    model.setRowCount(0); // Clear previous data
    fillTable(rs, model);
    rs.close();
    stmt.close();
    con.close();
}

private void fillTable(ResultSet rs, DefaultTableModel model) throws SQLException {
    ResultSetMetaData rsmd = rs.getMetaData();
    int columnsNumber = rsmd.getColumnCount();
    while (rs.next()) {
        Object[] rowData = new Object[columnsNumber];
        for (int i = 0; i < columnsNumber; i++) {
            rowData[i] = rs.getObject(i + 1);
        }
        model.addRow(rowData);
    }
}

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM person where username = '" + username + "' AND userpassword = '" + password + "';");
            while (rs.next()) {
                if (rs.getString("userrole").equals("Admin")) {

                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String userrole = rs.getString("userrole");
                    String email = rs.getString("email");
                    String dob = rs.getString("dob");
                    String address = rs.getString("address");
                    String phone = rs.getString("phone");
                    setVisible(false);
                    new adminDash(username, fname, lname, userrole,email,address,phone,dob).setVisible(true);
                }

                else if (rs.getString("userrole").equals("NGO")){
                    setVisible(false);
                    //set the ngo jframe to be visible
                }
                else {
                    setVisible(false);
                    //new RegisteredUserDashboard().setVisible(true);
                }
            }}
            catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnterValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterValueActionPerformed
  

    




    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpDesignation2;
    private javax.swing.JLabel EmpName2;
    private javax.swing.JTextField EnterValue;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn4;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn8;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JButton searchUserDetails;
    private javax.swing.JTextField searchUserID;
    private javax.swing.JPanel sidePanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    private String username = ""; 
    private String fname = ""; 
    private String lname = ""; 
    private String userrole = ""; 
    private String email = ""; 
    private String phone = ""; 
    private String address = ""; 
    private String dob = ""; 
    int myuserID = 0;
    static int updationUserID = 0;
    private String password = "";
}

